[package]
name = "racere"
version = "0.1.0"
edition = "2021"

[lib]
name = "racere"
path = "src/lib.rs"
test = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.29.0"
rand_distr = "0.4.2"